global.wavePlan = [
	{zombie: obj_Basic_Zombie ,amount: 25},
	{zombie: obj_Fast_Zombie,amount: 20},
	{zombie: obj_Basic_Zombie,amount: 10},
	{zombie: obj_Basic_Zombie,amount: 20},
	{zombie: obj_Basic_Zombie,amount: 30},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Case ,amount: 11},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2},
	{zombie: obj_Zombie_Boss1 ,amount: 2}
]