draw_rectangle(x-32,y-32,x+32,y+32,false)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_colour(c_black)
draw_text(x,y-5,healthPoints)
draw_text(x,y+5,resistant)
draw_set_colour(c_white)