draw_set_font(fnt_Agressive20);
draw_set_halign(fa_center);
draw_set_valign(fa_middle)
draw_set_colour(c_black)
draw_set_alpha(0.5)
draw_rectangle(room_width/2-228,0,room_width/2+228,room_height,false)
draw_set_colour(c_white)
draw_set_alpha(1)
draw_text_transformed(room_width/2,64,"settings",1,1,0);